### ISSUE TITLE
[BUG] preventOutsideInteraction is not working at all!

### ISSUE THREAD

**Issue by mohamedabkal** [xcarpentier/rn-tourguide#106]
the `preventOutsideInteraction` is not working.
I've the latest version `3.2.0`
```
<TourGuideProvider preventOutsideInteraction={true}>
    <Main />
</TourGuideProvider>
```
The issue seems to be happening because `preventOutsideInteraction` doesn't exist on `TourGuideProviderProps`, I can't even find anything from #81 PR in my node_modules/rn-tourguide.

**Comment by qaws5503** [comment]
I think the author hadn't build a new version of the changing in #81 .

**Comment by mohamedabkal** [comment]
Thank you for your help. I didn't pay attention to that but anyways I ended up using another library

**Comment by qaws5503** [comment]
@mohamedabkal Hey! The author has release the new versions, including this props.
You can give this library a try.
