### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by yousefshakoury** [xcarpentier/rn-tourguide#12]
I receive error `[Error: undefined Unable to resolve module `react-native-svg` from `node_modules\rn-tourguide\lib\components\SvgMask.js`: react-native-svg could not be found within the project.`

**Comment by xcarpentier** [comment]
Readme explains how to install: https://github.com/xcarpentier/rn-tourguide#installation

**Comment by thvbb** [comment]
> I receive error `[Error: undefined Unable to resolve module `react-native-svg`from`node_modules\rn-tourguide\lib\components\SvgMask.js`: react-native-svg could not be found within the project.`

Same on me
