### ISSUE TITLE
Android dark mode is switching the text color to white

### ISSUE THREAD

**Issue by gausss** [xcarpentier/rn-tourguide#150]
Hi,

on Android using dark mode the text color switches to white which makes it insivisble in the default settings (See screenshots). Is there a way to change the text color?

<img width="362" alt="Bildschirmfoto 2024-01-06 um 14 32 45" src="https://github.com/xcarpentier/rn-tourguide/assets/520764/1feb4bdc-30ee-4d38-8de7-a361330f1d2f">
<img width="359" alt="Bildschirmfoto 2024-01-06 um 14 32 27" src="https://github.com/xcarpentier/rn-tourguide/assets/520764/c906dccb-96ab-4088-acb5-f1e492de8f08">

**Comment by gausss** [comment]
I've implemented a custom tooltip component. It works although a bit more complicated than I'd hoped for.

**Comment by SoorajChoudhary** [comment]
@gausss Please provide me solution. I try for two days

**Comment by SoorajChoudhary** [comment]
Thanks
