### ISSUE TITLE
Ignore margin

### ISSUE THREAD

**Issue by lupenq** [xcarpentier/rn-tourguide#25]
Hello, friends!

I have a little question: can we ignore the margin in the TourGuideZone?

> Button step3 styles margin-top 24px
![image](https://user-images.githubusercontent.com/25533519/99268440-36f06000-2836-11eb-96d1-0557e2d49e33.png)

**Comment by xcarpentier** [comment]
Maybe wrap your buttons into a View wrapper that allow margin and use tour guide wrapper for your nested button... no?

**Comment by lupenq** [comment]
Thanks for the answer. I already guessed to do it. I just thought I could do this natively

**Comment by lupenq** [comment]
Thanks for attention. I think we can close the issue
