### ISSUE TITLE
getCurrentStep is undefined

### ISSUE THREAD

**Issue by kamaldeepj** [xcarpentier/rn-tourguide#41]
I'm trying to get the current step info using the `getCurrentStep` function `useTourGuideController`. The function occasionally returns the current step info but most of the times the function is undefined. Is there any way for me to get the current step?

**Comment by gerwim** [comment]
I have the same issue, however you can work around this using the event `handleOnStepChange`.

E.g.:

```
const {
  eventEmitter, // an object for listening some events
} = useTourGuideController()


const handleOnStepChange = (step) => {
  console.log(step.order) // <--- will contain the current step
}

React.useEffect(() => {
  eventEmitter.on('stepChange', handleOnStepChange)

  return () => {
    eventEmitter.off('stepChange', handleOnStepChange)
  }
}, [])
```
