### ISSUE TITLE
It is possible change color of buttons?

### ISSUE THREAD

**Issue by SergioSuarezDev** [xcarpentier/rn-tourguide#5]
Hi!

It is possible changue the color of text buttons without edit stye.js 
Using tooltipStyle ??

**Comment by xcarpentier** [comment]
Please use one of those to customize the tooltip component : 
- https://github.com/xcarpentier/rn-tourguide#custom-tooltip-styling
- https://github.com/xcarpentier/rn-tourguide#custom-tooltip-component

**Comment by SergioSuarezDev** [comment]
Thank you!
