### ISSUE TITLE
How can I style the labels of the tooltip?

### ISSUE THREAD

**Issue by ramzicoding** [xcarpentier/rn-tourguide#64]
I would like to change the style of the buttons Skip , next, previous etc. 
I would like to change the background color , text color, fontSize etc

**Comment by yukari1414** [comment]
You would need to pass in your own custom tooltip component ([reference](https://github.com/xcarpentier/rn-tourguide/blob/c22e6c339871f1bc67e858c0c140212f478b9658/src/components/Tooltip.tsx#L46)).
There's a [section in the readme](https://github.com/xcarpentier/rn-tourguide#custom-tooltip-component) that describes this.
